// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_VcVLTTwvT",
    "aws_user_pools_web_client_id": "23l0fe1a1nim8u5rjq4551ugki",
    "aws_appsync_graphqlEndpoint": "https://42nmkhz6gzhqlhht2z66bbwkxe.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
